// This file is auto-generated by scripts/sync-changelog.js
// Do not edit directly - update CHANGELOG.md instead

export interface ChangelogEntry {
  type: "major" | "minor" | "patch";
  description: string;
  commit?: string;
  commitUrl?: string;
  author?: string;
  authorUrl?: string;
  pr?: string;
}

export interface ChangelogSection {
  version: string;
  date?: string;
  changes: ChangelogEntry[];
}

export const changelog: ChangelogSection[] = [
  {
    version: "1.0.1",
    changes: [
      {
        type: "patch",
        commit: "8e88c59",
        commitUrl: "https://github.com/webbiffy/wui-design/commit/8e88c599e5b6e28113fea73303ebb4b08cde06ff",
        author: "webbiffy",
        authorUrl: "https://github.com/webbiffy",
        description: "initial release for wui design - react"
      }
    ]
  }
];
