// This file is auto-generated by scripts/sync-changelog.js
// Do not edit directly - update CHANGELOG.md instead

export interface ChangelogEntry {
  type: "major" | "minor" | "patch";
  description: string;
  commit?: string;
  commitUrl?: string;
  author?: string;
  authorUrl?: string;
  pr?: string;
}

export interface ChangelogSection {
  version: string;
  date?: string;
  changes: ChangelogEntry[];
}

export const changelog: ChangelogSection[] = [
  {
    version: "1.1.0",
    changes: [
      {
        type: "minor",
        description: "[#4](https://github.com/webbiffy/wui-design/pull/4) [`3f9730f`](https://github.com/webbiffy/wui-design/commit/3f9730f8ca91b291aec479c2b8a3c82679f585d5) Thanks [@webbiffy](https://github.com/webbiffy)! - ---"
      },
      {
        type: "patch",
        description: "[#4](https://github.com/webbiffy/wui-design/pull/4) [`3f9730f`](https://github.com/webbiffy/wui-design/commit/3f9730f8ca91b291aec479c2b8a3c82679f585d5) Thanks [@webbiffy](https://github.com/webbiffy)! - Add Badge component export"
      }
    ]
  },
  {
    version: "1.0.1",
    changes: [
      {
        type: "patch",
        commit: "8e88c59",
        commitUrl: "https://github.com/webbiffy/wui-design/commit/8e88c599e5b6e28113fea73303ebb4b08cde06ff",
        author: "webbiffy",
        authorUrl: "https://github.com/webbiffy",
        description: "initial release for wui design - react"
      }
    ]
  }
];
